### ISSUE TITLE
Can't play alarm

### ISSUE THREAD

**Issue by aintyourcat** [pickfire/spt#15]
Hello, thanks for the app, it's really helpful. But, i need a help, since I can't play any sound with it. I've read that playing sound is supported on the man page though. This command only gives me the notification:

![11-02-2020_05:28:22](https://user-images.githubusercontent.com/66950307/97816499-af9cdb80-1cd0-11eb-967a-f0c9ad8638e0.png)

Did i do anything wrong? I've tried to use a different file extension too.
I'm using:
1. spt v0.5 builded from the maste and btw the pkg from the Void Linux gives the same result too. 
2. PulseAudio

Thanks in advance!

**Comment by pickfire** [comment]
~~Are you sure `Email-01.wav` is there? Try `spt -e 'ls' -n 'notify-send'`?~~ Oh, `mpv` doesn't seemed to work for me too, last time I was trying out with aplay and I think it worked.

**Comment by pickfire** [comment]
I made a quick patch for this. I didn't notice the issue. Thanks for reporting the issue.

```bash
./spt -e "mpv 也可以.ogg" -n notify-send
```

**Comment by aintyourcat** [comment]
Thank you so much it works now :))

**Comment by pickfire** [comment]
Feel free to ping back after a few days so I can do a release if you find there is no issue.

**Comment by pickfire** [comment]
I pushed a new release for this, this is an important fix. Thanks again for reporting this issue. :D

https://github.com/pickfire/spt/releases/tag/0.6
