### ISSUE TITLE
Semantics: notifyext

### ISSUE THREAD

**Issue by VilleWitt** [pickfire/spt#17]
To improve the man page wording of notifyext, and notifycmd: what is the semantics of ext? external, or extra?
Source code says "extra", but conventionally ext would mean external.

**Comment by pickfire** [comment]
It is indeed extra since it is run separately in addition to notifycmd. Yes, the notifycmd part is a bit confusing since it will run the command in a specific way, as it sends the argument into the command, but notifyext just runs the command specified without additional arguments.

**Comment by pickfire** [comment]
Closing this since I don't know what should I do here.
