### ISSUE TITLE
How do I pass a “critical” argument for notify-send?

### ISSUE THREAD

**Issue by raihanadf** [pickfire/spt#21]
I want the notification to stay instead of disappearing every 10 seconds (in case Im doing something outside for a while). 

By passing the flag `-u critical` using `notify-send` the notification should not disappear only if I clicked it, but I don't know how and where to place the command. So, how do I pass the `-u critical` command to spt?

Thanks in advance!

**Comment by raihanadf** [comment]
Nevermind, I got it working now

![image](https://user-images.githubusercontent.com/12584890/200585839-a7b6bce9-3762-4c8d-9086-06cbe11bf281.png)

I simply read the libnotify [docs](https://www.manpagez.com/html/libnotify/libnotify-0.7.7/NotifyNotification.php#notify-notification-set-urgency) and added  `notify_notification_set_urgency (n, NOTIFY_URGENCY_CRITICAL)` line right after `NotifyNotification *n` variable in `notify_send(char *cmt)` function. Sorry for me being lazy hahahah

Closed.

**Comment by pickfire** [comment]
Or you can write a script to have it run `notify-send -u critical`, supposedly it should support passing arguments to `-n`.
