### ISSUE TITLE
Pause timer

### ISSUE THREAD

**Issue by antbbn** [pickfire/spt#4]
I am opening this issue since we started this discussion in my fork but I think this is the best place to continue.

So far we agree that Ctrl+z or SIGTSTP and SIGCONT is not a good solution since when stopped the process does not respond to SIGUSR1.

Maybe we can use SIGUSR2 to as a pause/play signal?
eg SIGUSR2 pauses if the timer is running, resumes if timer is paused.

**Comment by pickfire** [comment]
It is implemented now, but I think I still need to make it wait for the signal instead of `timecount += 0` every second. So I will just keep this opened for now.

**Comment by antbbn** [comment]
Yeah, that totally makes sense.
I will read up on signal waiting and come up with a better implementation :)
